WebASP/Controllers/CartController.cs
using WebASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebASP.Context;

namespace WebASP.Controllers
{
    public class CartController : Controller
    {
        WebAPSEntities4 objWebsiteBanHangEntities = new WebAPSEntities4();
        // GET: Cart
        public ActionResult Cart()
        {
            return View((List<CartModel>)Session["cart"]);
        }

        public ActionResult AddToCart(int id, int quantity)
        {
            if (Session["cart"] == null)
            {
                List<CartModel> cart = new List<CartModel>();
                cart.Add(new CartModel { Product = objWebsiteBanHangEntities.Products.Find(id), Quantity = quantity });
                Session["cart"] = cart;
                Session["count"] = 1;
            }
            else
            {
                List<CartModel> cart = (List<CartModel>)Session["cart"];
                //kiểm tra sản phẩm có tồn tại trong giỏ hàng chưa???
                int index = isExist(id);
                if (index != -1)
                {
                    //nếu sp tồn tại trong giỏ hàng thì cộng thêm số lượng
                    cart[index].Quantity += quantity;
                }
                else
                {
                    //nếu không tồn tại thì thêm sản phẩm vào giỏ hàng
                    cart.Add(new CartModel { Product = objWebsiteBanHangEntities.Products.Find(id), Quantity = quantity });
                    //Tính lại số sản phẩm trong giỏ hàng
                    Session["count"] = Convert.ToInt32(Session["count"]) + 1;
                }
                Session["cart"] = cart;
            }
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }

        private int isExist(int id)
        {
            List<CartModel> cart = (List<CartModel>)Session["cart"];
            for (int i = 0; i < cart.Count; i++)
                if (cart[i].Product.id.Equals(id))
                    return i;
            return -1;
        }

        //xóa sản phẩm khỏi giỏ hàng theo id
        public ActionResult Remove(int Id)
        {
            List<CartModel> li = (List<CartModel>)Session["cart"];
            li.RemoveAll(x => x.Product.id == Id);
            Session["cart"] = li;
            Session["count"] = Convert.ToInt32(Session["count"]) - 1;
            return Json(new { Message = "Thành công", JsonRequestBehavior.AllowGet });
        }
    }
}

WebASP/Controllers/PaymentController.cs
using WebASP.Context;
using WebASP.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebASP.Controllers
{
    public class PaymentController : Controller
    {
        // GET: Payment
        WebAPSEntities4 objASPNETEntities = new WebAPSEntities4();
        public ActionResult Index()
        {
            if (Session["idUser"] == null)
            {
                return RedirectToAction("Login", "Home");
            }
            else
            {
                // lấy thông tin từ giỏ hàng trong session
                var istCart = (List<CartModel>)Session["cart"];

                // tạo dữ liệu cho Order
                Order objOrder = new Order();
                objOrder.name = "DonHang-" + DateTime.Now.ToString("yyyyMMddHHmmss");
                objOrder.user_id = int.Parse(Session["idUser"].ToString());
                objOrder.created_at = DateTime.Now;
                objOrder.status = 17;

                objASPNETEntities.Orders.Add(objOrder);

                // lưu thông tin vào bảng Order
                objASPNETEntities.SaveChanges();

                // Lấy OrderId vừa tạo để lưu vào bảng OrderDetail
                int orderId = objOrder.id;
                List<OrderDetail> lstOrderDetail = new List<OrderDetail>();

                foreach (var item in istCart)
                {
                    OrderDetail obj = new OrderDetail();
                    obj.quantity = item.Quantity;
                    obj.order_id = orderId;
                    obj.product_id = item.Product.id;
                    lstOrderDetail.Add(obj);
                }

                objASPNETEntities.OrderDetails.AddRange(lstOrderDetail);
                objASPNETEntities.SaveChanges();
            }

            return View();
        }
    }
}

WebASP/Views/Cart/Cart.cshtml
@model IEnumerable<WebASP.Models.CartModel>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<script type="text/javascript">
    $(function () {
        $("#removecart").click(function () {
            var model = {};
            //lấy id sản phẩm
            model.Id = $("#productid").val();
            $.ajax({
                type: "POST",
                url: '@Url.Action("Remove", "Cart")',
                data:  JSON.stringify(model) ,
                dataType: "json",
                contentType: "application/json; charset=utf-8",
                success: function () {
                    $('#CartCount').text(@Session["count"] - 1);
                    $("#product-" + model.Id).remove();
                },
                error: function () {
                    alert("Lỗi trong khi thêm vào giỏ hàng!");
                }
            });
            return false;
        });
    });
</script>

<section class="section-content padding-y">
    <div class="container">
        <div class="row">
            <main class="col-md-9">
                <div class="card">

                    <table class="table table-borderless table-shopping-cart">
                        <thead class="text-muted">
                            <tr class="small text-uppercase">
                                <th scope="col">Product</th>
                                <th scope="col" width="120">Quantity</th>
                                <th scope="col" width="120">Price</th>
                                <th scope="col" class="text-right" width="200"> </th>
                            </tr>
                        </thead>
                        <tbody>
                            @if (Model != null)
                            {
                                foreach (var item in Model)
                                {
                                    <tr id="product-@item.Product.id">
                                        <td>
                                            <figure class="itemside">
                                                <div class="aside"><img src="~/Content/images/items/@item.Product.image" class="img-sm"></div>
                                                <figcaption class="info">
                                                    <a href="#" class="title text-dark">@item.Product.name</a>
                                                </figcaption>
                                            </figure>
                                        </td>
                                        <td>
                                            <input type="text" value="@item.Quantity" />
                                        </td>
                                        <td>
                                            <div class="price-wrap">
                                                <var class="price">@item.Product.price</var>
                                            </div> <!-- price-wrap .// -->
                                        </td>
                                        <td class="text-right">
                                            <input type="hidden" value="@item.Product.id" id="productid" />
                                            <a data-original-title="Save to Wishlist" title="" href="" class="btn btn-light" data-toggle="tooltip"> <i class="fa fa-heart"></i></a>

                                            <a href="" class="btn btn-light" id="removecart"> Remove</a>
                                        </td>
                                    </tr>
                                }
                            }
                            else
                            {
                                <p>Không có sản phẩm trong giỏ hàng</p>
                            }


                        </tbody>
                    </table>

                    <div class="card-body border-top">
                        <a href="@Url.Action("Index","Payment")" class="btn btn-primary float-md-right"> Thanh toán <i class="fa fa-chevron-right"></i> </a>
                        <a href="@Url.Action("Index","Home")" class="btn btn-light"> <i class="fa fa-chevron-left"></i> Tiếp tục mua hàng </a>
                    </div>
                </div> <!-- card.// -->

                <div class="alert alert-success mt-3">
                    <p class="icontext"><i class="icon text-success fa fa-truck"></i> Free Delivery within 1-2 weeks</p>
                </div>

            </main> <!-- col.// -->
            <aside class="col-md-3">
                <div class="card mb-3">
                    <div class="card-body">
                        <form>
                            <div class="form-group">
                                <label>Have coupon?</label>
                                <div class="input-group">
                                    <input type="text" class="form-control" name="" placeholder="Coupon code">
                                    <span class="input-group-append">
                                        <button class="btn btn-primary">Apply</button>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
                <div class="card">
                    <div class="card-body">
                        <dl class="dlist-align">
                            <dt>Total price:</dt>
                            <dd class="text-right">USD 568</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Discount:</dt>
                            <dd class="text-right">USD 658</dd>
                        </dl>
                        <dl class="dlist-align">
                            <dt>Total:</dt>
                            <dd class="text-right  h5"><strong>$1,650</strong></dd>
                        </dl>
                        <hr>
                        <p class="text-center mb-3">
                            <img src="images/misc/payments.png" height="26">
                        </p>

                    </div> <!-- card-body.// -->
                </div>  <!-- card .// -->
            </aside> <!-- col.// -->
        </div>

    </div> <!-- container .//  -->
</section>